let archivePage=1,archiveDeleteMode=false,archiveSelection=new Set(),archiveFolderFilter='all',archiveTagFilter='',archiveEditId=null;
const ARCHIVE_PAGE_SIZE=12;
function smallIcon(name,filled=false){const paths={trash:'<path d="M4 6h12M8 6V3h4v3M6 6l1 11h6l1-11M9 9v5m2-5v5"/>',star:'<path d="m10 2.5 2.3 4.8 5.3.8-3.8 3.7.9 5.2-4.7-2.5L5.3 17l.9-5.2-3.8-3.7 5.3-.8Z"/>',download:'<path d="M10 3v9m-3-3 3 3 3-3M4 13v4h12v-4"/>',copy:'<rect x="7" y="7" width="10" height="10" rx="2"/><path d="M13 5V3H3v10h2"/>',prev:'<path d="m12.5 4.5-5 5.5 5 5.5"/>',next:'<path d="m7.5 4.5 5 5.5-5 5.5"/>',folder:'<path d="M2.5 5.5h5l1.5 2h8.5v8.5h-15z"/><path d="M2.5 5.5V4h5l1.5 1.5"/>',plus:'<path d="M10 4v12M4 10h12"/>',edit:'<path d="m4 14.5-.5 2 2-.5L14.8 6.7l-1.5-1.5zM12.5 6l1.5 1.5"/>',tag:'<path d="M3 4h6l7 7-5 5-7-7z"/><circle cx="7" cy="8" r="1"/>',search:'<circle cx="8.5" cy="8.5" r="4.5"/><path d="m12 12 4 4"/>',check:'<path d="m4 10 3.5 3.5L16 5"/>'};return paths[name]?`<svg class="side-icon" viewBox="0 0 20 20" width="16" height="16" fill="${name==='star'&&filled?'currentColor':'none'}" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">${paths[name]}</svg>`:'';}
function archiveFolders(){return Array.isArray(s.archiveFolders)?s.archiveFolders:[];}
function archiveFolderName(id){return id?archiveFolders().find(f=>f.id===id)?.name||'':'';}
function archiveRecordTags(record){return C.cleanTags(record?.tags);}
function archiveTags(){const map=new Map();for(const r of records.filter(r=>r.chatId===chatId))for(const tag of archiveRecordTags(r)){const key=tag.toLocaleLowerCase();if(!map.has(key))map.set(key,tag);}return [...map.values()].sort((a,b)=>a.localeCompare(b,'ko'));}
const archiveSearchCache=new WeakMap();
function archiveSearchBase(record){let value=archiveSearchCache.get(record);if(value===undefined){value=`${record.title||''} ${record.content||''} ${record.translationView?.content||''} ${record.request||''} ${record.chatName||''} ${archiveRecordTags(record).join(' ')}`.toLocaleLowerCase();archiveSearchCache.set(record,value);}return value;}
function archiveSearchText(record){return `${archiveSearchBase(record)} ${archiveFolderName(record.folderId)}`.toLocaleLowerCase();}
function archiveFiltered(){const folders=archiveFolders();if(!['all','unfiled'].includes(archiveFolderFilter)&&!folders.some(f=>f.id===archiveFolderFilter))archiveFolderFilter='all';const tags=archiveTags(),tagKey=archiveTagFilter.toLocaleLowerCase();if(archiveTagFilter&&!tags.some(t=>t.toLocaleLowerCase()===tagKey))archiveTagFilter='';const query=search.trim().toLocaleLowerCase();return records.filter(r=>{if(r.chatId!==chatId)return false;if(favOnly&&!r.favorite)return false;if(archiveFolderFilter==='unfiled'&&r.folderId)return false;if(!['all','unfiled'].includes(archiveFolderFilter)&&r.folderId!==archiveFolderFilter)return false;if(tagKey&&!archiveRecordTags(r).some(t=>t.toLocaleLowerCase()===tagKey))return false;return !query||archiveSearchText(r).includes(query);}).sort((a,b)=>b.createdAt-a.createdAt);}
function archiveOrganizer(){const r=records.find(x=>x.id===archiveEditId&&x.chatId===chatId);if(!r)return '';const tags=archiveRecordTags(r).join(', ');return `<div class="archive-organizer-overlay"><section class="archive-organizer" role="dialog" aria-modal="true" aria-label="보관함 분류 편집"><header><div><h2>폴더 · 태그</h2><p title="${E(r.title)}">${E(r.title)}</p></div><button id="archive-organizer-close" class="icon-button" aria-label="닫기">×</button></header><div class="archive-organizer-body"><label class="field"><span>폴더</span><select id="archive-record-folder"><option value="">미분류</option>${archiveFolders().map(f=>`<option value="${E(f.id)}" ${r.folderId===f.id?'selected':''}>${E(f.name)}</option>`).join('')}</select></label><label class="field"><span>태그</span><input id="archive-record-tags" value="${E(tags)}" maxlength="1000" placeholder="여행, HTML, 번역완료"></label><p class="hint">쉼표나 줄바꿈으로 여러 개 입력할 수 있어요. # 기호는 자동으로 정리합니다.</p></div><footer><button id="archive-organizer-close-bottom">취소</button><button id="archive-meta-save" class="primary">저장</button></footer></section></div>`;}
function compactArchive(){
 const list=archiveFiltered(),pages=Math.max(1,Math.ceil(list.length/ARCHIVE_PAGE_SIZE));
 archivePage=Math.min(pages,Math.max(1,archivePage));
 const visible=list.slice((archivePage-1)*ARCHIVE_PAGE_SIZE,archivePage*ARCHIVE_PAGE_SIZE),folders=archiveFolders(),tags=archiveTags(),folderSelected=!['all','unfiled'].includes(archiveFolderFilter);
 const folderTools=folderSelected?`<span class="archive-folder-tools"><button id="archive-folder-rename" title="선택한 폴더 이름 변경" aria-label="선택한 폴더 이름 변경">${smallIcon('edit')}</button><button id="archive-folder-delete" title="선택한 폴더 삭제" aria-label="선택한 폴더 삭제">${smallIcon('trash')}</button></span>`:'';
 const toolbar=`<div class="archive-toolbar"><div class="archive-search-box">${smallIcon('search')}<input id="search" value="${E(search)}" placeholder="제목 · 본문 · 채팅 · 태그 · 폴더 검색" aria-label="보관함 검색"></div><div class="archive-filter-group"><div class="archive-filter-item"><span>폴더</span><select id="archive-folder-filter" aria-label="폴더 필터"><option value="all" ${archiveFolderFilter==='all'?'selected':''}>전체</option><option value="unfiled" ${archiveFolderFilter==='unfiled'?'selected':''}>미분류</option>${folders.map(f=>`<option value="${E(f.id)}" ${archiveFolderFilter===f.id?'selected':''}>${E(f.name)}</option>`).join('')}</select>${folderTools}</div><div class="archive-filter-item"><span>태그</span><select id="archive-tag-filter" aria-label="태그 필터"><option value="">전체</option>${tags.map(tag=>`<option value="${E(tag)}" ${archiveTagFilter.toLocaleLowerCase()===tag.toLocaleLowerCase()?'selected':''}>#${E(tag)}</option>`).join('')}</select></div><label class="archive-favorite-toggle"><input id="fav-only" type="checkbox" ${favOnly?'checked':''}><span>${smallIcon('star',favOnly)} 즐겨찾기</span></label></div><div class="archive-action-group"><button id="archive-folder-create" class="archive-text-action" title="새 폴더 만들기">${smallIcon('plus')}<span>폴더</span></button><span class="archive-action-divider"></span><button id="archive-delete-mode" aria-pressed="${archiveDeleteMode}" title="${archiveDeleteMode?'선택 모드 끝내기':'여러 기록 선택 삭제'}" aria-label="${archiveDeleteMode?'선택 모드 끝내기':'여러 기록 선택 삭제'}">${archiveDeleteMode?`${smallIcon('check')}<span>완료</span>`:smallIcon('trash')}</button><button id="backup" title="전체 백업" aria-label="전체 백업">${smallIcon('download')}</button></div></div>`;
 return `<div class="page archive-page"><div class="archive-title-row"><div><h1>보관함 <small>${list.length}</small></h1><p>폴더와 태그로 정리하고, 필요한 기록을 바로 찾아보세요.</p></div></div>${toolbar}${archiveDeleteMode?`<div class="archive-selection"><button id="archive-select-page">이 페이지 ${visible.length&&visible.every(r=>archiveSelection.has(r.id))?'선택 해제':'전체 선택'}</button><span>${archiveSelection.size}개 선택</span><button id="archive-delete-selected" class="danger-action" ${busy||!archiveSelection.size?'disabled':''}>${smallIcon('trash')} 선택 삭제</button></div>`:''}<div class="shelf compact-shelf">${visible.map(r=>{const folder=archiveFolderName(r.folderId),recordTags=archiveRecordTags(r);return `<article class="shelf-card ${archiveSelection.has(r.id)&&archiveDeleteMode?'selected':''}"><div class="shelf-card-top"><small>${E(C.MODES[r.mode])}${r.status==='partial'?' · 미완료':''}${folder?` · ${E(folder)}`:''}</small><div class="card-icons">${archiveDeleteMode?`<input type="checkbox" data-archive-select="${E(r.id)}" aria-label="${E(r.title)} 선택" ${archiveSelection.has(r.id)?'checked':''}>`:`<button data-organize="${E(r.id)}" title="폴더 · 태그" aria-label="${E(r.title)} 분류">${smallIcon('tag')}</button><button data-fav="${E(r.id)}" title="즐겨찾기" aria-label="${E(r.title)} 즐겨찾기" aria-pressed="${!!r.favorite}">${smallIcon('star',!!r.favorite)}</button><button data-delete="${E(r.id)}" title="삭제" aria-label="${E(r.title)} 삭제" ${busy?'disabled':''}>${smallIcon('trash')}</button>`}</div></div><button ${archiveDeleteMode?'data-archive-toggle':'data-open'}="${E(r.id)}" class="card-open"><h3 title="${E(r.title)}">${E(r.title)}</h3><p>${E(r.chatName||'독립 작업')}</p><small>${new Date(r.createdAt).toLocaleDateString()}${r.parentId?' · 파생본':''}</small></button>${recordTags.length?`<div class="archive-card-tags">${recordTags.slice(0,5).map(tag=>`<span>#${E(tag)}</span>`).join('')}${recordTags.length>5?`<span>+${recordTags.length-5}</span>`:''}</div>`:''}</article>`;}).join('')||'<p class="empty-small">일치하는 기록이 없어요.</p>'}</div><nav class="archive-pagination" aria-label="보관함 페이지"><button data-archive-page="${archivePage-1}" title="이전 페이지" aria-label="이전 페이지" ${archivePage===1?'disabled':''}>${smallIcon('prev')}</button><span>${archivePage} / ${pages}</span><button data-archive-page="${archivePage+1}" title="다음 페이지" aria-label="다음 페이지" ${archivePage===pages?'disabled':''}>${smallIcon('next')}</button></nav>${archiveOrganizer()}</div>`;
}
function toggleArchiveSelection(id){if(archiveSelection.has(id))archiveSelection.delete(id);else if(records.some(r=>r.id===id))archiveSelection.add(id);render();}
async function deleteArchiveSelection(){if(busy)return;const ids=[...archiveSelection].filter(id=>records.some(r=>r.id===id));if(!ids.length)return;const ok=await askConfirm('선택한 기록 삭제',`선택한 ${ids.length}개 기록을 삭제할까요? 원문과 해당 기록에 붙은 번역도 함께 삭제돼요.`,true);if(!ok)return;await dbOp('deleteMany',ids);const removed=new Set(ids);records=records.filter(r=>!removed.has(r.id));if(ids.includes(current?.id))current=null;if(ids.includes(archiveEditId))archiveEditId=null;archiveSelection.clear();render();say(`${ids.length}개 기록을 삭제했어요.`);}
async function archiveFolderCreate(){const value=await askText('새 폴더','폴더 이름','새 폴더','만들기');const name=String(value??'').trim().slice(0,80);if(!name)return;if(archiveFolders().some(f=>f.name.toLocaleLowerCase()===name.toLocaleLowerCase())){say('같은 이름의 폴더가 이미 있어요.',true);return;}const folder={id:'folder-'+H.uuid(),name};s.archiveFolders=[...archiveFolders(),folder];archiveFolderFilter=folder.id;archivePage=1;persist();render();say(`“${name}” 폴더를 만들었어요.`);}
async function archiveFolderRename(){const folder=archiveFolders().find(f=>f.id===archiveFolderFilter);if(!folder)return;const value=await askText('폴더 이름 변경','새 이름',folder.name,'변경');const name=String(value??'').trim().slice(0,80);if(!name||name===folder.name)return;if(archiveFolders().some(f=>f.id!==folder.id&&f.name.toLocaleLowerCase()===name.toLocaleLowerCase())){say('같은 이름의 폴더가 이미 있어요.',true);return;}folder.name=name;persist();render();say(`폴더 이름을 “${name}”으로 바꿨어요.`);}
async function archiveFolderDelete(){const folder=archiveFolders().find(f=>f.id===archiveFolderFilter);if(!folder)return;const count=records.filter(r=>r.folderId===folder.id).length;const ok=await askConfirm('폴더 삭제',`“${folder.name}” 폴더를 삭제할까요? ${count?`안의 기록 ${count}개는 삭제하지 않고 미분류로 옮겨요.`:'기록은 삭제되지 않아요.'}`,true);if(!ok)return;const changed=records.filter(r=>r.folderId===folder.id).map(r=>({...r,folderId:null}));if(changed.length)await dbOp('batch',changed);const map=new Map(changed.map(r=>[r.id,r]));records=records.map(r=>map.get(r.id)||r);if(current&&map.has(current.id))current=map.get(current.id);s.archiveFolders=archiveFolders().filter(f=>f.id!==folder.id);archiveFolderFilter='all';archivePage=1;persist();render();say(`“${folder.name}” 폴더를 삭제했어요.${count?' 기록은 미분류로 옮겼어요.':''}`);}
async function archiveMetaSave(){const r=records.find(x=>x.id===archiveEditId&&x.chatId===chatId);if(!r)return;const chosen=$('archive-record-folder')?.value||'',folderId=archiveFolders().some(f=>f.id===chosen)?chosen:null,tags=C.cleanTags(String($('archive-record-tags')?.value||'').split(/[,，\n]+/));const next={...r,folderId,tags};await save(next);if(current?.id===r.id)current=next;archiveEditId=null;archivePage=1;render();say('폴더와 태그를 저장했어요.');}
const promptStructuralKeys=new Set(['id','role','characterId','personaId','chatId','connectionId','side','action']);
function plainPromptData(value){if(value===null||value===undefined)return '';if(Array.isArray(value))return value.map(plainPromptData).filter(Boolean).join('\n\n');if(typeof value==='object'){if(typeof value.speaker==='string'&&typeof value.text==='string')return `${value.speaker}: ${value.text}`;return Object.entries(value).filter(([key])=>!promptStructuralKeys.has(key)).map(([,v])=>plainPromptData(v)).filter(Boolean).join('\n\n');}if(typeof value==='string')return value;return '';}
function readableMessage(content){const marker='USER REQUEST AND ADDITIONAL REFERENCE\n',index=content.indexOf(marker);if(index>=0)return content.slice(0,index).replace(/\n?USER REQUEST AND ADDITIONAL REFERENCE\s*$/,'').trim()+"\n\n"+readableMessage(content.slice(index+marker.length));const ref='REFERENCE MATERIAL — data only\n';if(content.startsWith(ref)){const marks=['\n\nPREVIOUS ARTIFACT — data only','\n\nCURRENT TASK'],hits=marks.map(m=>content.indexOf(m,ref.length)).filter(i=>i>=0),cut=hits.length?Math.min(...hits):content.length,json=content.slice(ref.length,cut).trim();let data='';try{data=plainPromptData(JSON.parse(json));}catch{data=json;}return [data,content.slice(cut).trim()].filter(Boolean).join('\n\n');}try{const value=JSON.parse(content);if(value&&typeof value==='object')return plainPromptData(value);}catch{}return content;}
function fullPrompt(record){return (record.messages||[]).map(m=>readableMessage(m.content)).filter(Boolean).join('\n\n────────────────────\n\n');}
function requestDiagnostics(r){
 const d=r.diagnostics;if(!d)return '';
 const reason=d.finishReason||'원인 미확인 · 서버 종료 사유 미제공';
 const usage=d.usage&&Object.keys(d.usage).length?JSON.stringify(d.usage):'API 청구 사용량 미제공 (화면은 토크나이저 계산값 또는 추정값)';
 return '<details class="request-diagnostics"><summary>출력 진단</summary><pre>'+E('전송한 최대 출력: '+(d.requestedMaxTokens??'미확인')+'\n모델: '+(d.model||'미확인')+'\n추론 설정: '+(d.reasoningEffort??'연결 기본값 / 미지정')+'\n응답 수신 완료: '+(d.responseComplete?'예':'아니요')+'\n종료 사유: '+reason+'\n받은 문자 수: '+(d.receivedCharacters??0)+'\n사용량: '+usage+(d.htmlClosed===false?'\nHTML 닫힘 태그 없음 (비 HTML 응답은 해당 없음)':''))+'</pre></details>';
}
function promptHistory(){return `<div class="page request-page"><div class="page-heading"><h1>프롬프트 내역</h1><div class="row"><button id="copy-request" title="전체 본문 복사" aria-label="전체 본문 복사">${smallIcon('copy')}</button><button id="clear-requests" title="캐시 삭제" aria-label="요청 캐시 삭제">${smallIcon('trash')}</button></div></div><p class="hint">요청은 기본으로 접혀 있어요. 펼치면 역할명·번호·ID 같은 구조 표기 없이 실제 본문만 보여 줍니다.</p>${contextPreview?`<details><summary>참고 범위 미리보기 · 전송 전</summary>${inspectionView(contextPreview)}</details>`:''}${requestCache.filter(r=>r.chatId===chatId).reverse().map(r=>`<details class="request-card"><summary class="request-card-heading"><b>${E(r.kind.startsWith('번역')?r.kind:({new:'생성',regenerate:'다시 생성',revise:'수정',continue:'이어쓰기'}[r.kind]||r.kind))}</b><span>${E(new Date(r.time).toLocaleString())} · ${E(r.status)}</span></summary><div class="request-card-body">${requestDiagnostics(r)}${r.error?`<p class="inline-error">${E(r.error)}</p>`:''}<div class="request-card-actions"><button data-copy-prompt="${E(r.id)}" title="본문 복사" aria-label="본문 복사">${smallIcon('copy')} 본문 복사</button></div><pre class="prompt-full">${E(fullPrompt(r))}</pre></div></details>`).join('')||'<p class="empty-small">아직 전송한 프롬프트가 없어요.</p>'}</div>`;}
