let referencesOpen=false,referenceTab='context',settingsTab='connections',promptTab='analysis',referenceBook='';
function chatModeName(mode){return mode==='conversation'?'대화':mode==='game'?'게임':'RP';}
function chatModeBadge(chat){return chat?`<span class="chat-mode-badge mode-${E(chat.mode||'roleplay')}">${chatModeName(chat.mode)}</span>`:'';}
function chatOptions(){const groups=[['conversation','대화'],['roleplay','RP'],['game','게임']];return groups.map(([mode,label])=>{const rows=chats.filter(c=>(c.mode||'roleplay')===mode);return rows.length?`<optgroup label="${label}">${rows.map(c=>opt(c.id,`[${label}] ${c.name||'이름 없는 채팅'}`,chatId)).join('')}</optgroup>`:'';}).join('');}
function currentChatLabel(){const c=chats.find(x=>x.id===chatId);return c?(c.mode==='conversation'?'현재 채팅 프롬프트':c.mode==='game'?'현재 게임 프롬프트':'현재 채팅 / 연결 프리셋'):'현재 채팅 설정';}
const chevron='<svg viewBox="0 0 16 16" width="16" height="16" fill="none" aria-hidden="true"><path d="m6 3 5 5-5 5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
function sectionTitle(title,action=''){return `<div class="section-title"><h3>${title}</h3>${action}</div>`;}
function presetControl(){return '<p class="hint">Side Story 전용 지침으로 생성해요. 실리태번 본편 프롬프트 프리셋의 자동 불러오기는 준비 중이에요.</p>';}

function currentCardView(){return characters.map(c=>`<span class="st-current-card">${c.avatar?`<img src="${E(SillyTavern.getContext().getThumbnailUrl?.('avatar',c.avatar)||'') }" alt="" loading="lazy">`:''}<span><b>${E(H.character(c).name)}</b><small>${E(c.id)}</small></span></span>`).join('');}
function referenceSummary(){const linked=chats.find(c=>c.id===chatId);return `<section class="compose-section">${sectionTitle('현재 채팅','<button id="open-references" class="text-action">참고 설정 '+chevron+'</button>')}<p class="selected-chat"><span>${E(linked?.name||'열린 채팅 없음')}</span></p><div class="st-current-cards">${currentCardView()}</div><div class="selected-tags">${personas.map(c=>`<span>페르소나 · ${E(H.character(c).name)}</span>`).join('')}<span>로어북 ${s.loreIds.length}</span></div></section>`;}
function referenceDialog(){if(!referencesOpen)return '';const tabs=[['context','대화 · 요약',''],['lore','로어북',s.loreIds.length],['request','추가 조건','']];const native=false;let body='';
if(referenceTab==='lore'){if(native)body='<div class="dialog-empty">현재 채팅에 연결된 월드인포를 참고해요.</div>';else{if(!s.loreIds.includes(referenceBook))referenceBook=s.loreIds[0]||'';body=`<div class="book-columns"><section><div class="list-heading">로어북 선택</div>${pickList('loreIds',lorebooks.map(l=>[l.id,l.name]))}</section><section><div class="list-heading">엔트리 선택 ${help('책만 선택하면 켜진 항목을 포함해요. 엔트리를 직접 체크하면 활성 조건과 관계없이 체크한 항목만 포함해요.')}</div>${s.loreIds.length?`<select id="reference-book">${s.loreIds.map(id=>opt(id,lorebooks.find(l=>l.id===id)?.name||id,referenceBook)).join('')}</select><div id="entries-${E(referenceBook)}">${loreEntriesView(referenceBook)}</div>`:'<p class="dialog-empty">먼저 로어북을 선택해 주세요.</p>'}</section></div>`;}}
if(referenceTab==='context')body=`<div class="dialog-fields"><div class="row">${field('참고 범위',native?'<select disabled><option>본편 설정 사용</option></select>':select('referenceMode',[['both','대화 + 요약'],['summary','요약만']]))}${field('대화 범위',select('scope',[['20','최근 20개'],['60','최근 60개'],['150','최근 150개'],['all','전체 · 토큰 한도 내']]))}</div><label class="check"><input type="checkbox" data-setting="includeSummary" ${s.includeSummary?'checked':''}>저장된 요약 포함</label>${field('직접 입력한 요약',`<textarea id="reference-summary" rows="9" placeholder="줄거리, 인물 관계, 중요한 사건을 적어 주세요.">${E(s.summaryByChat[chatId||'_none']||'')}</textarea>`)}</div>`;
if(referenceTab==='request')body=`<div class="dialog-fields">${field('분위기',`<input data-setting="tone" value="${E(s.tone)}" placeholder="담백하게, 긴장감 있게…">`)}${field('추가 조건',`<textarea data-setting="notes" rows="7" placeholder="이번 작업에 적용할 조건을 적어 주세요.">${E(s.notes)}</textarea>`)}<label class="check"><input type="checkbox" data-setting="pcControl" ${s.pcControl?'checked':''}>PC의 행동과 대사도 창작</label></div>`;
return `<div class="reference-overlay"><section class="reference-dialog" role="dialog" aria-modal="true" aria-labelledby="reference-title"><header><div><h2 id="reference-title">참고 자료</h2><p>이번 작업에 필요한 내용만 선택하세요.</p></div><button id="close-references" class="icon-close" aria-label="참고 자료 닫기">×</button></header><div class="reference-top"><div><span class="hint">현재 채팅의 캐릭터와 페르소나를 자동으로 참고해요.</span><div class="st-current-cards">${currentCardView()}</div></div></div><nav class="reference-tabs" aria-label="참고 자료 종류">${tabs.map(([key,label,n])=>`<button data-reference-tab="${key}" aria-pressed="${referenceTab===key}" class="${referenceTab===key?'active':''}">${label}${n!==''?`<small>${n}</small>`:''}</button>`).join('')}</nav><div class="reference-body">${body}</div><footer><div class="reference-bulk">${referenceTab==='lore'?`<button id="linked-picks">연결된 로어북 불러오기</button><button id="clear-picks">모두 해제</button>`:''}</div><button id="close-references-done" class="primary">완료</button></footer></section></div>`;}
function settingsSection(title,body,note=''){return `<section class="settings-card"><header><h2>${title}</h2>${note?`<p>${note}</p>`:''}</header><div class="settings-card-body">${body}</div></section>`;}
function tokenFields(){return tokenControls().replace(/^<details[^>]*><summary>[^<]*<\/summary>/,'').replace(/<\/details>$/,'');}
function settingsContent(){switch(settingsTab){
case 'connections':return settingsSection('API 연결','<button id="refresh" class="text-action">연결 목록 새로고침</button>'+generationConnection()+field('번역용 API 연결',select('translationConnectionId',[['','생성용 연결과 동일'],...connections.map(c=>[c.id,c.name+' · '+(c.model||c.provider)])])),'실리태번에 저장한 연결 프로필을 생성·번역에 각각 지정하세요. 목록에 없으면 연결 관리에서 프로필을 저장한 뒤 새로고침하세요.');
case 'generation':return settingsSection('분량과 토큰 한도',tokenFields()+'<p class="hint">입력 한도는 ST 토크나이저로 계산하며 메시지 여유분을 포함해요. 별도 프로필을 쓰더라도 계산은 현재 실리태번 연결 모델 기준이에요. 토크나이저를 사용할 수 없으면 추정값이라고 표시해요.</p>','분석·스토리·HTML은 토큰 목표를, 내면은 질문에 맞는 자연스러운 분량을 사용해요.');
case 'translation':return settingsSection('번역 설정',translationSettings().replace('<h2>번역</h2>',''),'원문은 보존하고 같은 결과 안에서 번역을 전환해요.');
case 'replacement':return settingsSection('정규식','<button id="open-replacements">정규식 설정</button><p class="hint">원문과 번역문에 적용하고, 발췌 이미지에서는 적용 여부를 따로 선택해요.</p>');
case 'reading':return settingsSection('분석 · 이야기',viewerControls(),'글의 모양만 바뀌며 저장 원문에는 영향을 주지 않아요.')+settingsSection('HTML',viewerControls(true),'기본은 HTML 자체의 스타일을 유지해요.');
case 'prompts':{const activeId=s.activeInstructionPresetIds?.[promptTab]||C.BUILTIN_INSTRUCTION_ID,builtin=activeId===C.BUILTIN_INSTRUCTION_ID,presetsForMode=s.instructionPresets.filter(p=>p.mode===promptTab),fixed=C.FIXED_MODE_RULES[promptTab]?.trim(),visualFixed=promptTab==='visual',fixedLabel=visualFixed?'Side Story 고정 기술 규칙':'Side Story 공통 출력 규칙',fixedHint=visualFixed?'HTML 완결성·sandbox·외부 리소스 제한처럼 뷰어 호환성에 필요한 규칙은 프리셋과 별도로 항상 적용돼요.':'텍스트 결과의 가벼운 Markdown 표시 규칙은 프리셋과 별도로 항상 적용돼요. 화면 전체를 꾸미는 HTML/CSS는 HTML 모드에서만 사용해요.',modeLabel=C.MODES[promptTab]||promptTab,draft=promptDrafts?.[promptTab]??s.prompts[promptTab]??'';return settingsSection(`${modeLabel} 지침 프리셋`,`${field('현재 프리셋',`<select id="instruction-preset-select"><option value="${C.BUILTIN_INSTRUCTION_ID}" ${builtin?'selected':''}>기본 · 내장</option>${presetsForMode.map(p=>opt(p.id,p.name,activeId)).join('')}</select>`)}<div class="preset-manage-actions"><button id="instruction-preset-clone">${builtin?'복제해서 새 프리셋':'새 프리셋으로 복제'}</button>${builtin?'':`<button id="instruction-preset-save" class="primary">저장</button><button id="instruction-preset-rename">이름 변경</button><button id="instruction-preset-delete" class="danger-action">삭제</button>`}</div><nav class="prompt-tabs">${Object.entries(C.MODES).map(([key,n])=>`<button data-prompt-tab="${key}" class="${promptTab===key?'active':''}" aria-pressed="${promptTab===key}">${n}</button>`).join('')}</nav>${field('작성 지침',`<textarea data-prompt="${promptTab}" rows="${fixed?'13':'17'}" maxlength="16000" ${builtin?'readonly':''}>${E(draft)}</textarea>`)}${builtin?'<p class="hint">내장 기본 지침은 잠겨 있어요. 복제하면 현재 항목 전용 프리셋으로 저장할 수 있어요.</p>':'<p class="hint">수정한 내용은 저장 버튼을 눌러 현재 프리셋에 반영해요.</p>'}${fixed?field(fixedLabel,`<textarea class="fixed-rules" rows="7" readonly>${E(fixed)}</textarea>`)+ `<p class="hint">${fixedHint}</p>`:''}`,`${modeLabel} 프리셋은 다른 항목과 별도로 저장돼요.`);}
case 'data':return settingsSection('백업과 복원',`<div class="backup-actions"><button id="backup">백업 내보내기</button><button id="restore" ${busy?'disabled':''}>백업 가져오기</button></div><input id="import-file" type="file" accept=".json" hidden><label class="check"><input id="restore-settings" type="checkbox">생성 설정도 함께 복원</label><p class="hint">브라우저 데이터를 지우기 전에 백업해 주세요. 요청 캐시와 API 키는 백업에 포함되지 않아요.</p>`)+settingsSection('요청 캐시','<button id="clear-requests">요청 캐시 삭제</button><p class="hint">보관함의 결과는 삭제하지 않아요.</p>');
}}
function redesignedSettings(){const tabs=[['connections','API 연결'],['generation','생성'],['translation','번역'],['reading','읽기'],['replacement','정규식'],['prompts','지침'],['data','데이터']];return `<div class="preferences"><header class="preferences-heading"><h1>설정</h1><span>일반 설정은 자동 저장되고, 지침은 저장 버튼으로 반영돼요.</span></header><div class="preferences-layout"><nav class="preferences-nav" aria-label="설정 분류">${tabs.map(([key,label])=>`<button data-settings-tab="${key}" class="${settingsTab===key?'active':''}" aria-pressed="${settingsTab===key}"><span>${label}</span>${chevron}</button>`).join('')}</nav><main class="preferences-content">${settingsContent()}</main></div></div>`;}
