let translationShown=false,translationDraft=null,contextPreview=null;
const loreEntryCache={},loreEntryErrors={};
function help(text){return `<details class="help"><summary aria-label="도움말">?</summary><div role="note">${E(text)}</div></details>`;}
function generationConnection(){return field('생성용 API 연결',select('connectionId',[['','채팅 연결 / 기본 연결'],...connections.map(c=>[c.id,c.name+' · '+(c.model||c.provider)])]));}
function pickList(key,items){return `<div class="pick-list">${items.map(([id,name])=>`<label><input type="checkbox" data-pick="${key}" value="${E(id)}" ${s[key].includes(id)?'checked':''}><span>${E(name)}</span></label>`).join('')||'<span class="hint">없음</span>'}</div>`;}
function loreEntriesView(id){if(loreEntryErrors[id])return `<p class="inline-error">${E(loreEntryErrors[id])}</p>`;if(!loreEntryCache[id])return '<p class="hint">불러오는 중…</p>';const entries=loreEntryCache[id],chosen=s.loreEntries[id]??entries.filter(e=>H.truth(e.enabled)).map(e=>e.id);return `<div class="lore-entry-actions"><button data-lore-bulk="all" data-lore-book="${E(id)}">전체 선택</button><button data-lore-bulk="none" data-lore-book="${E(id)}">전체 해제</button></div><p class="hint">직접 체크한 엔트리는 활성 키워드와 관계없이 포함해요.</p><div class="pick-list">${entries.map(e=>`<label><input type="checkbox" data-lore-entry="${E(id)}" value="${E(e.id)}" ${chosen.includes(e.id)?'checked':''}><span>${E(e.comment||e.name||'(제목 없음)')}</span></label>`).join('')||'엔트리 없음'}</div>`;}
async function loadLoreEntries({force=false}={}){await Promise.all(s.loreIds.map(async id=>{if(force){delete loreEntryCache[id];delete loreEntryErrors[id];}if(!loreEntryCache[id])try{loreEntryCache[id]=await get('/lorebooks/'+encodeURIComponent(id)+'/entries');delete loreEntryErrors[id];}catch(e){loreEntryErrors[id]=e.message;}const el=$('entries-'+id);if(el)el.innerHTML=loreEntriesView(id);}));}
function diagnosticsView(){return `<div class="page"><h1>상태 및 오류</h1><p>${E(notice||'준비됐어요.')}</p><details id="error-log" ${error?'open':''}><summary>최근 오류 상세</summary><button id="copy-error">복사</button><pre id="error-text">${E(error||'오류가 없어요.')}</pre></details></div>`;}
function inspectionView(info){const block=(title,value)=>{if(value===undefined||value===null||value==='')return '';return `<details class="reference-content"><summary>${E(title)}</summary><pre>${E(typeof value==='string'?value:JSON.stringify(value,null,2))}</pre></details>`;};const r=info.reference||{};return `<div class="request-summary"><span>프리셋 <b>${E(info.preset)}</b></span><span>연결된 채팅 <b>${E(info.chat||'없음')}</b></span></div>${info.source==='native'?'<p class="hint">본편 조립 모드예요. 아래 조립된 메시지가 실제 포함 내용이며, 서버가 개별 자료 목록을 별도로 반환하지 않아 카드·로어북 이름을 임의로 추정하지 않아요.</p>':`<div class="reference-tags">${(r.characters||[]).map(c=>`<span>캐릭터 · ${E(c.name)}</span>`).join('')}${(r.players||[]).map(c=>`<span>페르소나 · ${E(c.name)}</span>`).join('')}${(r.world||[]).map(b=>`<span>로어북 · ${E(b.name)} (${b.entries.length})</span>`).join('')}</div>`}${(r.characters||[]).map(c=>block('캐릭터 · '+c.name,c)).join('')}${(r.players||[]).map(c=>block('페르소나 · '+c.name,c)).join('')}${block('저장된 요약',r.summary)}${block('직접 입력한 요약',r.providedSummary)}${(r.world||[]).map(b=>block('로어북 · '+b.name,b.entries)).join('')}${block('참고 대화 · '+(r.dialogue?.length||0)+'개',r.dialogue?.length?r.dialogue:null)}${(info.presetMessages||[]).map((m,i)=>block((info.source==='native'?'본편 조립':'프리셋 지침')+' '+(i+1)+' · '+m.role,m.content)).join('')}${block('Side Story 지침',info.instructions)}${block('추가 조건',r.notes)}${block('이번 요청',info.task)}`;}
function displayRecord(){return current&&translationShown&&current.translationView?{...current,...current.translationView,translation:true}:current;}
function translationBar(){return `<div class="translation-bar" id="translation-bar"><button id="translation-original" class="${!translationShown?'active':''}">원문 보기</button><button id="translate" class="${translationShown?'active':''}" ${busy?'disabled':''}>${current.translationView?'번역 보기':'번역'}</button><button id="translation-edit" ${!current.translationView||busy?'disabled':''}>번역 편집</button>${translationShown?`<span>${E(current.translationView?.language||'')}</span>`:''}</div>`;}
function fitTranslationInput(el){if(!el)return;el.style.height='auto';const h=Math.max(34,Math.min(120,el.scrollHeight||34));el.style.height=h+'px';}
function switchTranslation(show){translationDraft=null;translationShown=show;editing=false;$('reader')?.classList.remove('translation-editor-open');render();}
function cancelTranslationEdit(){translationDraft=null;editing=false;$('reader')?.classList.remove('translation-editor-open');const el=$('editor');if(el){el.hidden=true;el.replaceChildren();}render();$('translation-edit')?.focus();}
function editTranslation(){if(!current?.translationView)return;disposeReading();if($('reader-tools'))$('reader-tools').open=false;translationShown=true;raw=false;editing=false;render();const plan=SideExtras.translationPlan(current.translationView.content,current.mode),originalPlan=SideExtras.translationPlan(current.content,current.mode),originalById=new Map(originalPlan.items.map(i=>[i.id,i.text]));translationDraft={plan,values:new Map(plan.items.map(i=>[i.id,i.text]))};editing=true;disposeReading();const el=$('editor'),reader=$('reader');reader?.classList.add('translation-editor-open');el.hidden=false;const rows=plan.items.map((i,index)=>{const original=originalById.get(i.id)??originalPlan.items[index]?.text??'';return `<article class="translation-edit-row"><div class="translation-edit-index">${index+1}</div><div class="translation-source"><span class="translation-cell-label">원문</span><div>${E(original)}</div></div><div class="translation-target"><label class="translation-cell-label" for="translation-item-${i.id}">번역문</label><textarea id="translation-item-${i.id}" class="translation-edit-input" data-translation-item="${i.id}" rows="1">${E(i.text)}</textarea></div></article>`;}).join('');el.innerHTML=`<div class="translation-edit-toolbar"><div><h3>번역 편집</h3><p class="hint">원문과 번역문을 나란히 확인해요. 번역문만 수정되며 HTML 구조는 유지돼요.</p></div><div class="translation-edit-actions"><button id="cancel-translation-edit" title="변경을 버리고 번역 화면으로 돌아가기">취소</button><button id="save-translation-edit" class="primary">저장</button></div></div><div class="translation-edit-columns"><span></span><b>원문</b><b>번역문</b></div><div class="translation-edit-list">${rows||'<p class="hint">편집할 번역 문단이 없어요.</p>'}</div>`;el.querySelectorAll('.translation-edit-input').forEach(fitTranslationInput);el.scrollIntoView({block:'start'});}
async function saveTranslationEdit(){if(!translationDraft||!current?.translationView)return;const original=current,epoch=viewEpoch;const content=translationDraft.plan.finish(translationDraft.values);if(current.mode==='visual')C.visual(content);const next={...current,translationView:{...current.translationView,content,editedAt:Date.now()}};await save(next);if(!alive||viewEpoch!==epoch||current?.id!==original.id)return;current=next;translationDraft=null;editing=false;translationShown=true;render();say('번역 수정을 저장했어요.');}
let savingImage=false;
async function saveImage(){
 if(savingImage)return;
 const result=$('result');if(!current||!result)throw new Error('저장할 출력 화면이 없어요.');
 if(editing)throw new Error('편집을 저장하거나 닫은 뒤 PNG로 저장해 주세요.');
 const name=(current.title||'Side-Story').replace(/[\\/:*?"<>|]/g,'_').slice(0,70),frame=result.querySelector('iframe');
 const button=$('save-image');savingImage=true;if(button)button.disabled=true;
 try{await flushReading();const blob=await SideHTML.png(frame||result);download(name+'.png',blob,'image/png');say('현재 출력 화면을 PNG로 저장했어요.');}
 finally{savingImage=false;if(button)button.disabled=false;}
}
