let requestCache=[];
const REQUEST_CACHE_KEY='st-sidestory-requests-v1';
try{const cached=JSON.parse(sessionStorage.getItem(REQUEST_CACHE_KEY)||'[]');if(Array.isArray(cached))requestCache=cached.slice(-5);}catch{}
function cacheSave(){try{sessionStorage.setItem(REQUEST_CACHE_KEY,JSON.stringify(requestCache));}catch{try{sessionStorage.removeItem(REQUEST_CACHE_KEY);}catch{}}}
function cacheRequest(payload,kind){const item={id:H.uuid(),time:new Date().toISOString(),chatId,kind,status:'전송 중',messages:structuredClone(payload.messages)};requestCache.push(item);while(requestCache.length>5||(requestCache.length>1&&JSON.stringify(requestCache).length>2000000))requestCache.shift();cacheSave();return item;}
function requestView(){return promptHistory();}
async function importLinked(){if(!chatId||chatId!==activeChat())throw new Error('현재 채팅에서 다시 열어 주세요.');const chat=await get('/chats/'+encodeURIComponent(chatId));s.loreIds=H.parseArray(chat.metadata?.activeLorebookIds);s.loreEntries={};persist();render();loadLoreEntries({force:true});}
function tokenControls(){return `<details class="token-options"><summary>토큰 한도</summary>${field('참고 자료 한도 · 토큰',`<input data-setting="contextBudget" type="number" min="1000" max="1000000" value="${s.contextBudget}">`)}${field('전체 입력 최대 · 추정 토큰',`<input data-setting="inputMaxTokens" type="number" min="1000" max="1000000" value="${s.inputMaxTokens}">`)}${field('최대 출력 요청 · 토큰',`<input data-setting="maxTokens" type="number" min="512" max="200000" value="${s.maxTokens}">`)}<p class="hint">Short 약 2,000 / Middle 약 6,000 / Long 약 10,000 토큰. 최대 출력 요청은 목표보다 넉넉하게 잡아 주세요. HTML 코드와 추론도 한도를 사용할 수 있어요. 모델·연결의 실제 지원 한도가 우선하며 20만을 모두 지원하는 것은 아니에요.</p><p class="hint">입력은 지침·자료·이전 결과·이번 요청을 합쳐 검사해요. 추정치는 실제 모델 토크나이저와 다를 수 있어요. 참고 자료 한도를 넘으면 캐릭터·요약·세계관 같은 고정 자료는 유지하고 오래된 대화부터 자동으로 제외해요. 전체 입력 한도도 과거 대화를 추가로 줄여 맞추며, 과거 대화를 모두 제외해도 고정 자료·프리셋·이전 결과가 한도를 넘을 때만 중단해요.</p></details>`;}
function viewerControls(visual=false){const input=(key,label,min,max,step=1)=>field(label,`<input type="number" data-setting="${key}" min="${min}" max="${max}" step="${step}" value="${s[key]}">`);const fonts=[['original','원본'],['system','시스템'],['sans','고딕'],['serif','명조'],['mono','고정폭']];return `${visual?`<label class="check"><input type="checkbox" data-setting="visualScripts" ${s.visualScripts?'checked':''}>격리된 HTML 상호작용 실행 (JS)</label><p class="hint">끄면 정적 화면만 표시해요. JS 화면의 번역 전환은 처음부터 다시 열려요. PNG 저장은 현재 화면 상태를 캡처해요.</p><label class="check"><input type="checkbox" data-setting="visualOverride" ${s.visualOverride?'checked':''}>HTML 읽기 설정 덮어쓰기</label>`:''}<div class="viewer-controls">${input(visual?'visualSize':'viewerSize','크기',10,28)}${field('글꼴',select(visual?'visualFont':'viewerFont',fonts))}${visual?'':input('viewerWidth','장평 (%)',75,125)}${input(visual?'visualSpacing':'viewerSpacing','자간 (px)',-2,6,.1)}${input(visual?'visualLine':'viewerLine','행높이',1,3,.05)}</div>${visual?'<p class="hint">기본은 HTML 원본 스타일을 유지해요. 덮어쓰기를 켜야 위 설정이 적용돼요.</p>':''}`;}
function translationSettings(){const builtin=s.activeTranslationPresetId===C.BUILTIN_TRANSLATION_ID;return `<h2>번역</h2>${field('번역용 API 연결',select('translationConnectionId',[['','생성용 연결과 동일'],...connections.map(c=>[c.id,c.name+' · '+(c.model||c.provider)])]))}${field('번역할 언어',`<input data-setting="translationLanguage" value="${E(s.translationLanguage)}" placeholder="한국어, English…">`)}${field('번역 최대 출력 요청 · 토큰',`<input type="number" data-setting="translationMaxTokens" min="512" max="200000" value="${s.translationMaxTokens}">`)}<p class="hint">최대 200,000까지 설정할 수 있어요. 모델 지원 한도가 우선해요. 긴 결과는 나누어 번역하므로 각 요청에 적용되는 한도예요. HTML은 텍스트만 번역하고 태그·스타일을 유지해요. 코드·스타일 블록은 번역하지 않아요. JS 안에서 만들어지는 문구는 번역 대상에서 제외돼요.</p>${field('번역 지침 프리셋',`<select id="translation-preset-select"><option value="${C.BUILTIN_TRANSLATION_ID}" ${builtin?'selected':''}>기본 · 내장</option>${s.translationPresets.map(p=>opt(p.id,p.name,s.activeTranslationPresetId)).join('')}</select>`)}<div class="preset-manage-actions"><button id="translation-preset-clone">${builtin?'복제해서 새 프리셋':'새 프리셋으로 복제'}</button>${builtin?'':`<button id="translation-preset-save" class="primary">저장</button><button id="translation-preset-cancel">변경 취소</button><button id="translation-preset-rename">이름 변경</button><button id="translation-preset-delete" class="danger-action">삭제</button>`}</div>${field('번역 지침 · 이름 표기와 말투 등',`<textarea id="translation-prompt-editor" rows="7" maxlength="12000" ${builtin?'readonly':''}>${E(builtin?SideExtras.TRANSLATE:translationPresetText())}</textarea>`)}<p id="translation-preset-status" class="hint">${translationPresetDirty()?'저장하지 않은 변경 사항이 있어요.':'저장된 지침을 사용 중이에요.'}</p><p class="hint">사용자 지침은 저장 버튼을 눌러 반영해요. 내장 지침은 잠겨 있어요. 복제하면 직역·말투 보존·고유명사 처리처럼 목적별 번역 프리셋을 만들 수 있어요. 항목 ID와 JSON 응답 형식은 구조 보존을 위해 별도로 적용돼요.</p>`;}
function usageLabel(r){const input=Number(r.inputTokens),output=Number(r.outputTokens),label=r.tokenizer?.label||'이전 기록 · 글자 수 추정';return `${Number.isFinite(input)?'입력 '+input.toLocaleString()+' · ':''}출력 ${(Number.isFinite(output)?output:SideExtras.tokens(r.content)).toLocaleString()} 토큰 · ${label}`;}
async function sendGeneration(payload,options,kind,onText=()=>{},counter=stHost.tokenCounter(payload.connectionId)){
 const count=await counter.messages(payload.messages);if(controller.signal.aborted)throw new DOMException("중단됨","AbortError");if(count>options.inputMaxTokens)throw new Error(kind.startsWith('번역')?`번역 입력 약 ${count.toLocaleString()} 추정 토큰이 최대 ${options.inputMaxTokens.toLocaleString()} 토큰을 넘었어요. 입력 한도를 높여 주세요.`:`과거 대화를 자동으로 제외한 뒤에도 전체 입력 약 ${count.toLocaleString()} 추정 토큰이 최대 ${options.inputMaxTokens.toLocaleString()} 토큰을 넘었어요. 고정 자료나 입력 한도를 확인해 주세요.`);
 if(payload.messages.some(m=>m.content.length>490000))throw new Error('단일 메시지가 서버 전송 한도를 넘었어요. 자료를 나눠 주세요.');
 const entry=cacheRequest(payload,kind);
 entry.diagnostics={tokenizer:counter.info(),inputTokens:count,requestedMaxTokens:payload.parameters?.maxTokens,reasoningEffort:payload.parameters?.reasoningEffort??null,connectionId:payload.connectionId,model:connections.find(c=>c.id===payload.connectionId)?.model||'',responseComplete:false};
 try{const text=await stHost.generate(payload,controller.signal);onText(text);entry.diagnostics.responseComplete=true;entry.diagnostics.receivedCharacters=text.length;entry.status='완료';entry.diagnostics.htmlClosed=/<\/body\s*>\s*<\/html\s*>\s*$/i.test(text.trim().replace(/\s*```$/,''));cacheSave();return text;}catch(e){entry.status=e.name==='AbortError'?'중단':'실패';entry.error=e.message;cacheSave();throw e;}
}
async function translateCurrent(){
 if(busy||!current)return;if(!chatId||chatId!==activeChat()||current.chatId!==chatId)throw new Error('현재 채팅의 결과만 번역할 수 있어요.');const original=current,viewIdAtStart=current.id,viewEpochAtStart=viewEpoch,options=C.settings(s),language=options.translationLanguage.trim();if(!language)throw new Error('설정에서 번역할 언어를 입력해 주세요.');
 const plan=SideExtras.translationPlan(original.content,original.mode);if(!plan.items.length)throw new Error('번역할 텍스트가 없어요.');
 const instruction=[C.translationPrompt(options,SideExtras.TRANSLATE),original.mode!=='visual'?'Preserve existing Markdown formatting in the source text.':'',SideExtras.TRANSLATE_CONTRACT,'Translate to: '+language].filter(Boolean).join('\n');
 const available=Math.min(8000,Math.floor((options.inputMaxTokens-SideExtras.tokens(instruction)-256)/2),Math.floor((options.translationMaxTokens-256)/3));if(available<64)throw new Error('번역 지침에 비해 입력/출력 한도가 작아요. 한도를 높여 주세요.');
 const chunks=SideExtras.batches(plan.items,available),translated=new Map();let input=0,output=0;
 busy=true;busyTask='translation';editing=false;page='create';mobilePane='result';controller=new AbortController();runConnection='';runId='';render();
 try{let cid=options.translationConnectionId||options.connectionId||original.settings?.connectionId;if(!cid&&original.chatId)cid=(await get('/chats/'+encodeURIComponent(original.chatId),controller.signal)).connectionId;cid=cid||connections.find(c=>H.truth(c.isDefault))?.id;if(!cid)throw new Error('번역에 사용할 AI 연결을 선택해 주세요.');runConnection=cid;const counter=stHost.tokenCounter(cid);
 for(let i=0;i<chunks.length;i++){if(controller.signal.aborted)throw new DOMException('중단됨','AbortError');say(`번역 중 · ${i+1}/${chunks.length} · 완성 후 한 번에 표시해요.`);runId=H.uuid();const messages=[{role:'system',content:instruction},{role:'user',content:JSON.stringify({items:chunks[i].map(({id,text})=>({id,text}))})}];input+=await counter.messages(messages);const result=await sendGeneration({connectionId:cid,messages,parameters:{maxTokens:options.translationMaxTokens},streaming:false,runId},options,'번역 '+(i+1)+'/'+chunks.length,()=>{},counter);output+=await counter.text(result);const parsed=SideExtras.parseTranslation(result,chunks[i]);for(const item of chunks[i]){const id=item.sourceId??item.id,text=parsed.get(item.id);translated.set(id,(translated.get(id)||'')+text);}}
 const content=plan.finish(translated);if(original.mode==='visual')C.visual(content);const record={...original,translationView:{content,language,batches:chunks.length,inputTokens:input,outputTokens:output,tokenizer:counter.info(),createdAt:Date.now()}};await save(record);if(viewEpoch===viewEpochAtStart&&current?.id===viewIdAtStart){current=record;translationShown=true;raw=false;}say('번역 완료 · 원문과 번역을 전환할 수 있어요.');
 }catch(e){if(viewEpoch===viewEpochAtStart&&current?.id===viewIdAtStart)current=original;say(e.name==='AbortError'?'번역 결과 수신을 중단했어요. 원문은 유지하며 API 처리는 계속될 수 있어요.':e.message,true);}finally{busy=false;busyTask='';controller=null;runId='';runConnection='';if(alive)render();}
}
